-- Generic, owner-only storage for the v3 recorder. Apply only in a user-owned CloudBase database.
create or replace function public.fitness_set_updated_at() returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end; $$;

create table public.training_sessions (id uuid primary key, owner_id text not null default auth.uid(), training_date date not null, training_day text not null, plan_version text not null, plan_snapshot jsonb not null default '{}'::jsonb, status text not null default 'draft' check(status in ('draft','completed')), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(owner_id,training_date,training_day,plan_version));
create table public.training_exercises (id uuid primary key, owner_id text not null default auth.uid(), session_id uuid not null references public.training_sessions(id) on delete cascade, sort_order integer not null, planned_snapshot jsonb not null default '{}'::jsonb, actual_name text, is_skipped boolean not null default false, adjustment_reason text, problem_note text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(session_id,sort_order));
create table public.training_sets (id uuid primary key, owner_id text not null default auth.uid(), exercise_id uuid not null references public.training_exercises(id) on delete cascade, set_number integer not null, weight_text text, reps integer, rpe numeric(4,2) check(rpe between 0 and 10), note text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(exercise_id,set_number));
create table public.training_agent_jobs (id uuid primary key, owner_id text not null default auth.uid(), session_id uuid not null references public.training_sessions(id) on delete cascade, status text not null default 'queued' check(status in ('queued','processing','needs_input','completed','failed')), input_snapshot jsonb not null default '{}'::jsonb, result jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.cardio_sessions (id uuid primary key, owner_id text not null default auth.uid(), performed_on date not null, activity_type text not null check(activity_type in ('stairs','run','swim','custom')), duration_minutes numeric(8,2), amount_value numeric(12,2), amount_unit text, rpe numeric(4,2) check(rpe is null or rpe between 0 and 10), note text, status text not null default 'draft' check(status in ('draft','completed')), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.nutrition_meals (id uuid primary key, owner_id text not null default auth.uid(), consumed_on date not null, meal_type text not null, meal_name text, pre_meal_note text, storage_bucket text, object_key text, image_mime text, image_size_bytes integer, photo_refs jsonb not null default '[]'::jsonb, estimate jsonb check(estimate is null or jsonb_typeof(estimate)='object'), consumed_estimate jsonb check(consumed_estimate is null or jsonb_typeof(consumed_estimate)='object'), confirmed_nutrition jsonb check(confirmed_nutrition is null or jsonb_typeof(confirmed_nutrition)='object'), after_object_key text, after_image_mime text, after_image_size_bytes integer, after_captured_at timestamptz, consumption_note text, consumption_status text not null default 'not_requested' check(consumption_status in ('not_requested','pending_agent','processing','needs_confirmation','confirmed','failed')), status text not null default 'pending_agent' check(status in ('pending_agent','processing','needs_confirmation','confirmed','failed')), confirmed_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.nutrition_meal_photos (id uuid primary key, owner_id text not null default auth.uid(), meal_id uuid not null references public.nutrition_meals(id) on delete cascade, storage_bucket text not null, object_key text not null, image_mime text not null, image_size_bytes integer not null check(image_size_bytes between 1 and 8388608), captured_at timestamptz not null default now(), created_at timestamptz not null default now(), unique(meal_id,object_key));
create table public.nutrition_agent_jobs (id uuid primary key, owner_id text not null default auth.uid(), reference_id uuid, job_type text not null check(job_type in ('meal_analysis','meal_consumption_analysis','weekly_review')), status text not null default 'queued' check(status in ('queued','processing','needs_input','completed','failed')), result jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
-- Web-client compatibility fields. These are explicit rather than inferred so
-- a self-hosted adapter can use the same contract as the local-first UI.
alter table public.training_sessions add column week_number integer not null default 1, add column current_exercise_index integer not null default 0, add column bodyweight_kg numeric(6,2), add column overall_feeling text, add column notes text, add column pain_or_abnormal text, add column completed_at timestamptz, add column client_revision bigint not null default 1;
alter table public.training_exercises add column exercise_key text, add column planned_name text, add column actual_weight numeric(8,2), add column actual_weight_text text, add column weight_unit text not null default 'kg', add column actual_sets integer, add column actual_reps text, add column overall_rpe numeric(4,2), add column is_replaced boolean not null default false, add column status text not null default 'pending', add column completed_at timestamptz;
alter table public.training_sets add column weight numeric(8,2), add column is_completed boolean not null default false;
alter table public.cardio_sessions add column performed_time time, add column timing_basis text, add column mode text, add column swim_style text, add column pool_length_m numeric(7,2), add column length_count integer, add column avg_heart_rate smallint, add column problem_note text, add column notes text, add column client_revision bigint not null default 1;
create table public.nutrition_profiles (owner_id text primary key default auth.uid(), sex text, age integer, height_cm numeric(5,1), current_weight_kg numeric(5,1), activity_factor numeric(4,2), deficit_percent numeric(4,3), contract_version integer not null default 1, calibration_state text not null default 'baseline', current_target jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.nutrition_daily_targets (id uuid primary key, owner_id text not null default auth.uid(), target_date date not null, day_type text not null, training_name text, calories integer, carbs_g integer, protein_g integer, fat_g integer, source text, contract_version integer not null default 1, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(owner_id,target_date));
create table public.nutrition_body_metrics (id uuid primary key, owner_id text not null default auth.uid(), measured_on date not null, weight_kg numeric(5,1), waist_cm numeric(5,1), note text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(owner_id,measured_on));
create table public.nutrition_weekly_reviews (id uuid primary key, owner_id text not null default auth.uid(), week_start date not null, week_end date not null, adherence_days integer, input_snapshot jsonb not null default '{}'::jsonb, agent_decision jsonb, previous_target jsonb, next_target jsonb, decision_status text not null default 'queued', contract_version_before integer not null default 1, contract_version_after integer, decided_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(owner_id,week_start));
create unique index nutrition_agent_jobs_one_active_job on public.nutrition_agent_jobs(owner_id,job_type,reference_id) where status in ('queued','processing');
create or replace function public.queue_nutrition_meal_consumption(p_meal_id uuid,p_job_id uuid,p_note text default null,p_after_object_key text default null,p_after_image_mime text default null,p_after_image_size_bytes integer default null,p_after_captured_at timestamptz default null) returns uuid language plpgsql security invoker set search_path=public,pg_temp as $$ declare v_owner text:=auth.uid(); begin if v_owner is null then raise exception 'authentication_required'; end if; if not exists(select 1 from nutrition_meals where id=p_meal_id and owner_id=v_owner and estimate is not null) then raise exception 'meal_not_found_or_unestimated'; end if; if exists(select 1 from nutrition_agent_jobs where owner_id=v_owner and reference_id=p_meal_id and job_type='meal_consumption_analysis' and status in ('queued','processing')) then raise exception 'meal_active'; end if; update nutrition_meals set consumption_note=nullif(btrim(p_note),''),after_object_key=p_after_object_key,after_image_mime=p_after_image_mime,after_image_size_bytes=p_after_image_size_bytes,after_captured_at=p_after_captured_at,consumed_estimate=null,consumption_status='pending_agent',updated_at=now() where id=p_meal_id and owner_id=v_owner; insert into nutrition_agent_jobs(id,owner_id,reference_id,job_type,status) values(p_job_id,v_owner,p_meal_id,'meal_consumption_analysis','queued'); return p_job_id; end $$;
do $$ declare t text; begin foreach t in array array['training_sessions','training_exercises','training_sets','training_agent_jobs','cardio_sessions','nutrition_meals','nutrition_meal_photos','nutrition_agent_jobs','nutrition_profiles','nutrition_daily_targets','nutrition_body_metrics','nutrition_weekly_reviews'] loop execute format('alter table public.%I enable row level security',t); execute format('grant select,insert,update,delete on public.%I to authenticated',t); execute format('create policy %I on public.%I for all to authenticated using (owner_id=auth.uid()) with check (owner_id=auth.uid())',t||'_owner_only',t); if t <> 'nutrition_meal_photos' then execute format('create trigger %I before update on public.%I for each row execute function public.fitness_set_updated_at()',t||'_updated_at',t); end if; end loop; end $$;
